### ISSUE TITLE
Add a crypto miner or ransomware option

### ISSUE THREAD

**Issue by Lenn133** [Blank-c/Umbral-Stealer#11]
It would really nice if you would add one of these :D

**Comment by Resisst** [comment]
dude its a stealer not a ransomware or crypto miner 💀

**Comment by Blank-c** [comment]
Well yeah thats true.

**Comment by Lenn133** [comment]
But it would be a nice Feature

**Comment by Blank-c** [comment]
Sorry but I'd like it to say stealer and nothing much advanced. This was literally a dead project but its gaining some attention recently.

**Comment by LocalSmail** [comment]
> But it would be a nice Feature

It would be nice if you made it your self lol

**Comment by LocalSmail** [comment]
> Sorry but I'd like it to say stealer and nothing much advanced. This was literally a dead project but its gaining some attention recently.

Old things usually get attention here and there.
