### ISSUE TITLE
Discord Token Stealing Related Stuff

### ISSUE THREAD

**Issue by UnrealNoodle** [Blank-c/Umbral-Stealer#14]
Can you tell me a simple python or batch code that gets the discord token, billing info and all those stuff from discord?
My discord so we can talk about this faster -> <<<Diya<3#5424

**Comment by Blank-c** [comment]
You may see the code of my other stealer https://github.com/Blank-c/Blank-Grabber

**Comment by UnrealNoodle** [comment]
i tried to remake it but i kept failing, i want a python script that grabs all discord related stuff like tokens, gmail, phone number, save it to a text file which will then be sent to a webhook.

**Comment by Blank-c** [comment]
Sorry I dom't use discord anymore. I have telegram if you want a direct talk.

The `Discord` class in my project (that I mentioned) does exactly this. You should put it in a different file and analyse it thoroughly.

**Comment by UnrealNoodle** [comment]
alright send me the invite
