### ISSUE TITLE
Icon selection

### ISSUE THREAD

**Issue by lITronusIl** [Blank-c/Umbral-Stealer#2]
Hi, if i select an icon, the builder freezes. Besides that, its not detected by my virus. Good Job!

**Comment by Blank-c** [comment]
Can you give more information regarding this issue? When you click on the select icon button, does it open the dialog to let you select and icon, or does it freeze as soon as you click on the button?

**Comment by lITronusIl** [comment]
Nothing blocks the icon, and i cant see the box because ill get a windows promt saying program not reacting

**Comment by Blank-c** [comment]
I am not able to reproduce the error (even in my VMs).
Which windows version are you using? Have you tried to wait for the program to unfreeze?

**Comment by Blank-c** [comment]
You there?
