### ISSUE TITLE
GUI keeps saying webhook not working when discord webhook has been used is functional on other programmes

### ISSUE THREAD

**Issue by Cabn32** [Blank-c/Umbral-Stealer#20]

**Comment by Cabn32** [comment]
GUI says webhook not working but it works on other programs

**Comment by Blank-c** [comment]
Can you send screenshot?

**Comment by Cabn32** [comment]
![image](https://github.com/Blank-c/Umbral-Stealer/assets/85973617/3ccd5c07-657d-45d0-bf98-1c7144aa1ba8)

**Comment by Cabn32** [comment]
But exact same webhook working on other programmes

**Comment by Blank-c** [comment]
Can you type this in cmd `curl <yourwebhook>`

The error means that its having problem while connecting to even discord, not that the webhook is wrong.

**Comment by Cabn32** [comment]
curl <https://discord.com/api/webhooks/1123965220168138884/DBKUBSy1VlBtY5o7dKIezPad4Z_l2u4HXb9BEoB5EkbR-Q3OS0uxj0McT3lHj0bEIxeW>
The syntax of the command is incorrect.

**Comment by Blank-c** [comment]
Can you put screenshot, the command works perfectly for me.

**Comment by Cabn32** [comment]
![image](https://github.com/Blank-c/Umbral-Stealer/assets/85973617/5d7365d4-b573-441e-a878-2e8569f02a1b)

**Comment by Blank-c** [comment]
Dont put the < and >

**Comment by Cabn32** [comment]
after i get the response from cmd what do i do

It looks like this

{"application_id": null, "avatar": null, "channel_id": "1123642938644250637", "guild_id": "11236429..644250634", "id": "11239...0168138884", "name": "Umbral", "type": 1, "user": {"id": "85381...9439193139", "username": "cabn49", "avatar": "61e09bf61eb87a793b7d61ccf99a7f69", "discriminator": "0", "public_flags": 64, "flags": 64, "banner": null, "accent_color": 14211298, "global_name": "Cabn", "avatar_decoration": null, "display_name": "Cabn", "banner_color": "#d8d2"}, "token": "DBKUBSy1VlBtY5o7dKIezPad4Z_l2u4HXb9BEoB5EkbR-Q...", "url": "https://discord.com/api/webhooks/1123965220168138884/DBKUBSy1Vl...KIezPad4Z_l2u4HXb9BEoB5EkbR-Q3OS0uxj0McT3lHj0bEIxeW"}

**Comment by Blank-c** [comment]
Hmm, can you see your firewall is blocking the app/try to use a VM like appsonfly VM

**Comment by Cabn32** [comment]
is it ok if i use virtualbox

**Comment by Blank-c** [comment]
> is it ok if i use virtualbox

I'd recommend appsonfly VM since in virtualbox, the network of you and the VM will be the same (which is probably the cause of it is not working).

**Comment by Cabn32** [comment]
oh ok 
 but appsonfly is paid and i cant do the free trial

**Comment by Blank-c** [comment]
> oh ok but appsonfly is paid and i cant do the free trial

no appsonfly is free

**Comment by Blank-c** [comment]
Get it [here](https://app.apponfly.com/trial)

**Comment by Cabn32** [comment]
![image](https://github.com/Blank-c/Umbral-Stealer/assets/85973617/e626de2f-953f-4784-8d62-68339b4fa5de)

**Comment by Blank-c** [comment]
It usually takes like 5 seconds.

**Comment by Cabn32** [comment]
its stil going lol
![image](https://github.com/Blank-c/Umbral-Stealer/assets/85973617/a7fd5dba-0467-4cf5-a001-3473fc316c6f)

**Comment by Blank-c** [comment]
> its stil going lol ![image](https://user-images.githubusercontent.com/85973617/249799033-a7fd5dba-0467-4cf5-a001-3473fc316c6f.png)

Do you have a VPN?

**Comment by Cabn32** [comment]
no

**Comment by Blank-c** [comment]
Try to use one. I think something is wrong with your Internet connection.

**Comment by Dakudek** [comment]
hey bro can u add my dis kubek56
