### ISSUE TITLE
Unknown user on Discord

### ISSUE THREAD

**Issue by DennisMihaltan** [Blank-c/Umbral-Stealer#23]
I don't know why, but I have some infos of a random PC user (from: Region: Hlavní město Praha
Country: Czechia
Timezone: Europe/Prague) on my Discord server, and I am from Italy... why?

**Comment by Blank-c** [comment]
Someone (or maybe you) have uploaded the file on virustotal. Your file was then ran in different VMs and you got the info of those VMs.

**Comment by DennisMihaltan** [comment]
nope... I build it, and tested it on my Laptop, and it works (correct infos), but a few hours later, appear unknown infos (I don't share it anyone)

**Comment by Blank-c** [comment]
Did you upload it on virustotal? Or sent someone?
Maybe you have uploaded a previous build?

**Comment by DennisMihaltan** [comment]
nope
