### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 8FrMc** [Blank-c/Umbral-Stealer#3]
when i run the built exe nothing happens and i can see the code of the builded file with dnspy...

**Comment by Blank-c** [comment]
Can you try to build again without "Anti VM" option.
Also, which version of windows are you using?

**Comment by Blank-c** [comment]
Stale

**Comment by 8FrMc** [comment]
win 10 bruh

**Comment by Blank-c** [comment]
Did you try to disable the Anti VM option?
