### ISSUE TITLE
Add crypto stealers

### ISSUE THREAD

**Issue by dustindog101** [Blank-c/Umbral-Stealer#7]
Add crypto stealer please. relatively simple

**Comment by EbaAaZ** [comment]
do you want me to help you integrate cry^pto i have two crypto-clipperwhit easy instalation or migrating in code let me know if your intersted

**Comment by Blank-c** [comment]
It would be nice of you if you can explain how it works.

**Comment by EbaAaZ** [comment]
ok but only to you add me on telegram and im not going to show you exaclty how as i work hard for the knowledge but i will give you three tool and a code to  integrated go read the manuel of the tool and you will be able to integrate any code to your code not only that but really understand what you do and why you do. that will be my thank you for your code, you just have to give me 5-6h before i can do it im little busy right now, 

leave me a public gpg key here i will send you info whit your key

To generate a key pair (public key and private key) using GnuPG (GPG) on Windows, follow these steps:

    Download and install Gpg4win from the official website: https://gpg4win.org/

    Open the Command Prompt (cmd.exe) as administrator. You can do this by searching for "cmd" in the Start menu, right-clicking on "Command Prompt," and selecting "Run as administrator."

    Run the following command to generate a key pair. Replace "Your Name" and "[your.email@example.com](mailto:your.email@example.com)" with your personal information:

bash

gpg --quick-generate-key "Your Name <your.email@example.com>" rsa4096

    To export the public key to a file, run the following command. Replace "[your.email@example.com](mailto:your.email@example.com)" with the email address you used when generating the key and "public_key.asc" with the name of the file in which you want to save the public key:

bash

gpg --output public_key.asc --armor --export your.email@example.com

Now, you have generated a key pair (public key and private key) and exported the public key to a file. You can share the public key with others so they can encrypt messages for you. Keep your private key secure and never share it with anyone else.

To generate a key pair (public key and private key) using GnuPG (GPG) on Linux, follow these steps:

    Install GnuPG if you haven't done so already. On most Linux distributions, you can use the following command:

bash

sudo apt-get install gnupg

On macOS, you can install GPG with Homebrew:

bash

brew install gnupg

    Run the following command to generate a key pair. Replace "Your Name" and "[your.email@example.com](mailto:your.email@example.com)" with your personal information:

bash

gpg --quick-generate-key "Your Name <your.email@example.com>" rsa4096

    To export the public key to a file, run the following command. Replace "[your.email@example.com](mailto:your.email@example.com)" with the email address you used when generating the key and "public_key.asc" with the name of the file in which you want to save the public key:

bash

gpg --output public_key.asc --armor --export your.email@example.com

Now, you have generated a key pair (public key and private key) and exported the public key to a file. You can share the public key with others so they can encrypt messages for you. Keep your private key secure and never share it with anyone else

talk to you later.

**Comment by Blank-c** [comment]
Thanks for the info but I will work it out myself.

From what I understand, crypto clipper waits for the user to copy a wallet address, then try to identify which type of wallet is that and replace the address on his clipboard with our.

**Comment by EbaAaZ** [comment]
the one that i have it better beacause it not actually stealing in account i make my code hook on the belt of other miner it took money but before it go into any account it still stealling but make my conscience better i guess and i dont know lol whatever take care
thank you again

**Comment by jamiekarvans** [comment]
> It would be nice of you if you can explain how it works.

i think you already know about the clipper, so i'm going to skip that,
but there is another wallet stealer which works like this : you can add the path of various wallets to grab just like browser data,
here is the path of some wallets:

Atomic wallet : {roaming}/atomic/Local Storage/leveldb
Exodus wallet : {roaming}/Exodus/exodus.wallet
and so on ...
by grabbing the files in this folders and replacing the files you recieved to your own app folder in your system you can simply get access to the wallets except if the user has set password for the app you will not know about it and you have to enter it, but usually from my exprience it always is one of the passwords that you've already recovered from the user's browser, ( using same passwords for the app aswell) and if not, then you can add a clipper so simply give the path of the exe file of each wallet and if the app is running and user is on it and logging in, simply activate the the keylogging if user manually enters it or get clipboard data if the user copy and paste it and send to webhook.
if you want to talk about it or have some ideas you can send me message, i will answer it.

**Comment by Blank-c** [comment]
Oh I understand. I'll think about it when I get time.

**Comment by dustindog101** [comment]
someone make a pull request

**Comment by Blank-c** [comment]
Added.
