### ISSUE TITLE
Startup is not works.

### ISSUE THREAD

**Issue by Meko1046** [Blank-c/Umbral-Stealer#8]
the startup is not works.

**Comment by Freeze-sys** [comment]
Add me Cloud#4458 dm me

**Comment by Blank-c** [comment]
After running the stub with the startup option enabled, can you check if the stub is in your `shell:common startup` folder?

**Comment by Blank-c** [comment]
I checked it, the startup is buggy. Please don't use it until I release next update (when I get time, I am busy these days).
